### ISSUE TITLE
关于 mr 的问题

### ISSUE THREAD

**Issue by LiuLingFei** [yotouch/pylon#68]
在使用 mr 过程中碰到一个比较奇怪的问题：调用 getEntity 查询出的 entity 调用 mr 是没问题的，调用 dbSession.queryRawSql 查询出来的 entity 调用 mr  查询不到数据。   @yinwm 
以 tag 功能为例：
```
//数据表结构：
tag:
    fields:
      childTags:
        fieldType: MULTI_REFERENCE
        targetMetaEntity: tag
      name:
        dataType: STRING
        displayName: 标签名字
      type:
        dataType: STRING
        displayName: 标签类型(group为标签组)
      picture:
        dataType: STRING
        displayName: 标签配图
```
```
//调用 dbSession.queryRawSql 代码获取 childs.size = 0
List<Entity> tagGroups = dbSession.queryRawSql("tag", "type=? and status=? order by createdAt desc", new Object[]{"group", Consts.STATUS_NORMAL}) ;
for(Entity group : tagGroups){
        List<Entity> childs = group.mr(dbSession, "childTags") ;
}
//调用 dbSession.getEntity 代码获取 childs.size > 0
Entity group = dbSession.getEntity("tag", uuid) ;
List<Entity> childs = group.mr(dbSession, "childTags") ;
```
